#  Aprendendo Closure - Parte 1

Essas série se chama "Aprendendo Closure" pois eu estou de fato aprendendo clojure e essas são minhas notas de estudo. Futuramente colocarem um blog ou no medium. Então se for acompanha( caso não encontre outra fonte que te agrade e por algum motivo você quiser ver as notas de alguem que assim como você começou sem saber nada da linguagem) tente seguir linearmente, assim podera identificar quando eu me auto corrigir em algum conceito mal fixado.
Primeiro vamos passar pelas funções basicas de aritméticas. 


In [2]:
(+ 10 9)

19

> Important:Em clojure não precisamos usar virgulas, mas caso queira usa-lás tbm é algo possivel

In [3]:
(+,10,9)

19

Para subtrações continuamos na mesma notação, o operador vem primeiro

In [4]:
(- 10 9)

1

Divisão:

In [5]:
(/ 24 4)

6

Multiplicação:

In [6]:
(* 11 11)

121

Clojure meio que usa uma notação matematica, então assim como fazemos pra resolver equações matematicas resolvendo os

Parenteses interiores primeiro de dentro pra fora. Em lisp não é diferente

Dessa forma a expressão abaixo é calculada primeiro multiplicação ``` (* 2 2)```  resultando ``` 4 ```, depois a 
soma ``` (+ 1 2) ``` resultando ```3``` e então finalmente a soma geral ``` (+ 3 4)``` que resulta em ```7```

In [7]:
(+ (+ 1 2) (* 2 2))

7

Pra criar uma variável devemos usar ``` def ``` como usado abaixo

In [8]:
(def a 10)

#'user/a

Acima criamos uma variavel ```a``` de valor ```10```

Em clojure as listas são representadas por ``` () ``` ,os vetores são representados por ``` []``` Em clojure as listas são representadas por ``` () ``` ,os vetores são representados por ``` [] ```
, os sets e maps são representados ``` {} ```

Para criarmos uma lista vazia ```l``` basta executar o seguinte comando:

In [9]:
(def l '())

#'user/l

Você deve está se perguntando o por que da ``` ' ``` , porem como deve ter reparado as expressões de clojure sempre vão dentro de ```()```, alias por ser um dialeto de lisp que nada mais é que list processing. Porem assim como na expressão ```(+ 1 2)``` as listas ficam dentro de ```()``` e sempre que o interpretador do clojure se depara com parenteses ele espera que o primeiro elemento seja uma função seguida pelos seus argumentos do tipo: ```(fn arg arg)```. Usamos o ```'``` apenas para dizer o interpretador da linguagem que não se trata de uma função e sim uma lista.

Alem de criar uma lista vazia, também é possivel que criemos uma lista com alguns elementos dentro, vejamos:

In [10]:
(def m '(1 2 3 4))

#'user/m

Se for necessario adcionar um item em uma lista , usamos ```cons```

In [11]:
(cons 2 '(1 2 3))

(2 1 2 3)

Como é possivel notar acima, clojure adciona o elemento na primeira posição, alias em clojure ao contrario de python e semelhante a Clang as listas são listas linkas. O que significa que para adcionar um item na ultima posição de uma lista o clojure deveria pecorrer todas as posições da lista.

Explicando melhor, uma lista linkada significa que o primeiro elemento armazena a posição na memoria do segundo elemento, o segundo elemento armazena a posição na memoria do terceiro elemento, e assim ....


Além de usar o vetor descrito, podemos usar o nome do vetor com ```cons``` :

In [12]:
(cons 2 m)

(2 1 2 3 4)

porem é interessante notar que o vetor ```m``` não é alterado. Pois em clojure trabalhamos com dados imultaveis.

In [13]:
m

(1 2 3 4)

se quisermos remover um item de uma lista podemos usar ```peek``` que irá remover o primeiro item.

In [14]:
(peek m)

1

Pop nos mostra todos os item fora o primeiro de uma lista. Lembrando que como uma list é linkada a partir da primera posição é normal que as funções de manipulação trabalhem a partir da primeira posição. Isso é diferente para vetores que veremos mais a seguir, pois vetores tem acesso via índice:

In [15]:
(pop m)

(2 3 4)

## Vetores

Vamos falar sobre vetores agora e pra começar podemos notar algumas similaridades com listas. Por exemplo para definir um vetor ```a``` vazio fazemos da seguinte forma:

In [16]:
(def a [])

#'user/a

Podemos criar um vetor ```b``` com alguns itens.

In [17]:
(def b [1 2 3 4])

#'user/b

Para adcionar um item no vetor, diferente das listas onde usamos ```cons``` usaremos ```conj``` e diferentes das listas passamos o vetor como primeiro argumento ```(conj [] argx)```:

In [18]:
(conj [1 2 3] 4)

[1 2 3 4]

Importante notar que diferentemente das listas um vetor adciona um novo elemento na sua ultima posição

Semelhante as listas , também é possível aplicar peek and pop em um vetor. Exemplos abaixo:

In [19]:
(peek [12 14 13])

13

In [20]:
(pop [12 14 13])

[12 14]

Nos vetores também é possível acessar um item pelo seu indice:

In [21]:
(get [3 19 12 15 10 21 24 35 56] 1)

19

In [22]:
(get [3 19 12 15 10 21 24 35 56] 0)

3

> Importante lembrar que em computação os indices normalmente começam no 0

Para adcionar itens em determinadas posição de um vetor podemos usar ```assoc```

In [24]:
(assoc [1 2 3 5 8] 5 13)

[1 2 3 5 8 13]

No exemplo acima, apenas mandamos o interpretador colocar o numero 13 na 5 posição. Pois usando ```assoc``` é possível colocar o elemento em qualquer posição apenas setando o índice.

> Importante: Caso você queira colocar o elemento na ultima posição sem setar o índice , use o ```conj``` já mostrado nesse post

```nth``` retorna o valor passando como argumento o índice

In [26]:
(nth [1 4 5 6 8 9] 5) 

9

Caso queira remover um valor támbem é possivel usar ```pop``` pois retorna um vetor sem o ultimo elemento

In [1]:
(pop [1 43 34 65 23])

[1 43 34 65]

In [1]:
(def a [[1 2 3 ] [4 5 6] [7 8 9]])

#'user/a

[[1 2 3] [4 5 6] [7 8 9]]

In [7]:
list (get a 0)

[1 2 3]

In [5]:
(assoc [1 2 3] 

Execution error (ArityException) at user/eval3970 (REPL:1).
Wrong number of args (2) passed to: clojure.core/assoc--5416


class clojure.lang.ArityException: 

removendo elemento do meio de vetor:

In [3]:
(defn remove [n coll]
(->> coll
     (map vector (iterate inc 1))
     (map #(zero? (mod (first %) n)))
     (map second)))

#'user/remove

Também temos a função ```replace``` que funciona substituindo os valores. A setença fica como ```replace vetor indices```: 

In [68]:
(def b [12 14 15])
(replace b [1 2 0])

[14 15 12]

## Maps

Vamos estudar um pouco de ```map``` . Para definir um map fazemos:

In [47]:
(def nilberth {:nome "nilberth souza" :idade 21})

#'user/nilberth

Para acessar , podemos simplesmente acessar pela chave que retorna um valor usando ```get``` :

In [29]:
(get nilberth :nome)

"nilberth souza"

In [30]:
(get nilberth :idade)

20

In [31]:
(def clientes {:nome ["Marcos" "Antonio" "Larissa"] :idade [21 22 19]})

#'user/clientes

In [32]:
(get clientes :nome)

["Marcos" "Antonio" "Larissa"]

In [33]:
(get clientes :idade)

[21 22 19]

Se você não quer que retorne apenas o valor, você pode usar ```find``` pra retorna a chave e o valor:

In [35]:
(find clientes :idade)

[:idade [21 22 19]]

In [36]:
(assoc clientes :divida [1000 1200 1200])

{:nome ["Marcos" "Antonio" "Larissa"], :idade [21 22 19], :divida [1000 1200 1200]}

In [38]:
(def cliente {:marcos {:nome "Marcos Castro" :idade 21 :Divida 1000} :joana {:nome "Joana Maria" :idade 32 :divida 2000}})

#'user/cliente

In [39]:
(get cliente :marcos)

{:nome "Marcos Castro", :idade 21, :Divida 1000}

In [41]:
(get (get cliente :marcos) :nome)

"Marcos Castro"

In [43]:
(dissoc cliente :joana)

{:marcos {:nome "Marcos Castro", :idade 21, :Divida 1000}}

In [46]:
(assoc cliente :arthur {:nome "Arthur Arcanjo" :idade 29 :divida 4000})

{:marcos {:nome "Marcos Castro", :idade 21, :Divida 1000}, :joana {:nome "Joana Maria", :idade 32, :divida 2000}, :arthur {:nome "Arthur Arcanjo", :idade 29, :divida 4000}}

Se quisermos acessarmos campos especificos de uma ```map``` devemos usar ```select-keys```. Usando os conhecimentos adquiridos até agora vamos acessar ```
cliente {:marcos {:nome "Marcos Castro" :idade 21 :Divida 1000} :joana {:nome "Joana Maria" :idade 32 :divida 2000}}```. Para usarmos ```select-key``` devemos montar a seguinte sentença:
``` select-key map [:key :key]```

Como nosso map clientes é uma map de maps. Primeiro usaremos ```get cliente :nome``` que retorna um map como primeiro argumento do ```select-keys``` e depois passamos em um vetor as chaves internas do cliente em especifico

In [54]:
(select-keys (get cliente :joana) [:idade :divida])

{:idade 32, :divida 2000}

Assim como nos vetores podemos usar a função ```replace``` porem passamos as keyword(mais abaixo hávera uma explicação sobre o que é keyword) como argumento na ordem que queremos re-organizar. 

Vejamos abaixo que ```select-keys``` quando passamos ```:marcos``` e ```:joana``` como paramentro retorna um map com os maps individuais de marcos e joana.

In [77]:
(select-keys cliente [:marcos :joana])

{:marcos {:nome "Marcos Castro", :idade 21, :Divida 1000}, :joana {:nome "Joana Maria", :idade 32, :divida 2000}}

In [79]:
(replace (select-keys cliente [:marcos :joana]) [:joana :marcos])

[{:nome "Joana Maria", :idade 32, :divida 2000} {:nome "Marcos Castro", :idade 21, :Divida 1000}]

> Lembrando que usei a função replace nesse caso na saida da função select-keys apenas pra demosntrar a funcionalidade. Recomendo que durante a leitura desse post que você por editar e casar as funções, alterar argumentos para que exercite o pensamento crítico. Pois é assim que comecei essas anotações

Temos que usar o ```get client :nome ``` primeiro , se não o resultado seria o abaixo. 

In [52]:
(select-keys cliente [:joana])

{:joana {:nome "Joana Maria", :idade 32, :divida 2000}}

Podemos checar se um cliente em especifico está no nosso map usando ```contains``` :

In [58]:
(contains? cliente :marcos)

true

Usando ```keys``` podemos ver quais chaves temos em nosso map:

In [59]:
(keys cliente)

(:marcos :joana)

In [62]:
(keys (get cliente :joana))

(:nome :idade :divida)

Usando ```vals``` podemos ver quais são os valores que temos no nosso map:

In [65]:
(vals cliente)

({:nome "Marcos Castro", :idade 21, :Divida 1000} {:nome "Joana Maria", :idade 32, :divida 2000})

In [66]:
(vals (get cliente :marcos))

("Marcos Castro" 21 1000)

Nos maps estamos usando keyswords que são as strings que começam com ```:``` . Keywords ocupam apenas um espaço na memoria, enquanto strings sempre vão ocupar o numero de vezes que for repetida. Porem é possivel converter strings em keywords e keywords em strings 


In [56]:
(keyword "Palavra")

:Palavra

O contrario também é verdadeiro:

In [57]:
(name :Palavra)

"Palavra"

## Simbolos

Até agora nos criamos estruturas pra indentificar clientes usando maps, porem é possivel fazer isso de uma forma bem simples usando structs:

In [84]:
(def pessoa (create-struct :nome :idade :saldo))

#'user/person

In [85]:
(struct pessoa "Nilberth" 21 1000)

{:nome "Nilberth", :idade 21, :saldo 1000}

tbm podemos usar uma macro do clojure que desempenha a mesma função

In [86]:
(defstruct vaca :codigo :idade :raca )

#'user/vaca

In [87]:
struct vaca "mimosa" 2 "nelore"

"nelore"

## Set

Podemos criar um set da seguinte forma:

In [2]:
(set [1 1 1 1 2 3 3 2 5 6 7 6 7 4 8])

#{7 1 4 6 3 2 5 8}

In [4]:
(apply sorted-set (set [1 5 3 4 5 6 7 4 4 7 8 9 0 9 4 3 ]))

#{0 1 3 4 5 6 7 8 9}

In [5]:
(conj #{1 2 3 4} 4)

#{1 4 3 2}

In [6]:
(disj #{1 2 3 4} 4)

#{1 3 2}

In [7]:
(def foo 
    (fn [p]
        (prn
            (str "Hello " p  "!"))))

#'user/foo

In [9]:
(foo "NIL")

"Hello NIL!"


nil

In [10]:
(let [xyz "testando"])

(prn xyz)

Syntax error compiling at (REPL:3:1).
Unable to resolve symbol: xyz in this context


class clojure.lang.Compiler$CompilerException: 